In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [4]:
x1

array([16,  6, 10, 12,  1, 15, 19, 10,  9, 15, 18, 11,  9,  4,  1, 16,  3,
        3, 16, 18, 15, 10, 15,  7, 12,  4,  5, 15,  8,  7,  6,  6, 11, 16,
        4, 19, 15,  7, 10, 16,  6, 11, 16, 10,  7,  7, 17,  4,  3,  9])

In [5]:
x2

array([ 2, 10,  7,  5,  8, 13, 10, 10, 19,  5,  3,  8,  6, 12, 17, 16, 13,
       19,  1,  7,  5, 18, 17,  7,  1,  7, 14, 17,  6,  8, 15, 16, 12,  1,
       15,  9, 19, 18, 17,  6,  9, 14, 18, 17, 10,  3,  1,  1, 19,  4])

In [6]:
y=3+2*x1-4*x2+np.random.random((50,))

In [7]:
np.random.random((50,))

array([0.39088309, 0.24633908, 0.23601977, 0.37640282, 0.63579122,
       0.61945974, 0.05958891, 0.8333304 , 0.42677535, 0.40386643,
       0.52259358, 0.71081171, 0.55889271, 0.94694484, 0.40730042,
       0.2183924 , 0.04303707, 0.47924813, 0.72104014, 0.15253422,
       0.79736605, 0.19980447, 0.2967194 , 0.98393768, 0.94166351,
       0.46895075, 0.07965313, 0.17492061, 0.89107857, 0.11240509,
       0.22844741, 0.96320453, 0.03537967, 0.44121868, 0.22846352,
       0.03732754, 0.92023081, 0.94282308, 0.35716083, 0.98560496,
       0.79803391, 0.52382778, 0.43358631, 0.76459532, 0.20134693,
       0.3929115 , 0.84432509, 0.38641767, 0.90173802, 0.98197024])

In [8]:
y

array([ 27.74320906, -24.81422111,  -4.93857061,   7.78880621,
       -26.26649498, -18.21907206,   1.52827049, -16.92191209,
       -54.79258744,  13.49641618,  27.10234278,  -6.57302335,
        -2.7924711 , -36.57115983, -62.08936085, -28.4614841 ,
       -42.51172737, -66.68524504,  31.6060394 ,  11.42066758,
        13.63536263, -48.10593215, -34.56903062, -10.41726458,
        23.4470569 , -16.37718359, -42.77035402, -34.27011862,
        -4.60285954, -14.64518312, -44.51740789, -48.02067698,
       -22.84712803,  31.85528596, -48.55759434,   5.51395148,
       -42.88161924, -54.86676285, -44.48300649,  11.4131214 ,
       -20.48060754, -30.8241771 , -36.1028935 , -44.6969609 ,
       -22.40371182,   5.17352867,  33.17711589,   7.91789093,
       -66.71162474,   5.42750565])

In [9]:
x1

array([16,  6, 10, 12,  1, 15, 19, 10,  9, 15, 18, 11,  9,  4,  1, 16,  3,
        3, 16, 18, 15, 10, 15,  7, 12,  4,  5, 15,  8,  7,  6,  6, 11, 16,
        4, 19, 15,  7, 10, 16,  6, 11, 16, 10,  7,  7, 17,  4,  3,  9])

In [10]:
x2

array([ 2, 10,  7,  5,  8, 13, 10, 10, 19,  5,  3,  8,  6, 12, 17, 16, 13,
       19,  1,  7,  5, 18, 17,  7,  1,  7, 14, 17,  6,  8, 15, 16, 12,  1,
       15,  9, 19, 18, 17,  6,  9, 14, 18, 17, 10,  3,  1,  1, 19,  4])

In [11]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1])

In [12]:
x
w


array([0., 0., 0.])

In [15]:
x.shape

(50, 3)

In [ ]:
x.head()

In [16]:
y.shape

(50,)

intercept  x1  x2
0          1  16   2
1          1   6  10
2          1  10   7
3          1  12   5
4          1   1   8

### calculating predicted Y
###  (beta)*X

In [146]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)




In [148]:
temp1=myprediction(x,w)

print(temp1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [125]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [126]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)


In [127]:
y

array([-32.715996  , -26.9354392 ,   1.94238858, -24.50631512,
       -32.84415036,   1.23335999, -40.65712656, -38.77531846,
       -60.445592  , -34.22758981, -68.31597962,   1.79785312,
        -4.43020809, -56.68637757,   1.41699822,  17.43610861,
       -10.14160518, -12.11215359, -60.52999597, -24.13089308,
       -24.66598274,   5.81628301, -20.32242349,  -6.97227272,
       -40.18471258, -30.25964604,  19.913334  , -30.5507443 ,
         9.61448365,  -0.72127203, -42.74442157, -62.2698523 ,
        -2.74302748, -44.25939433, -12.43326528, -44.96339304,
       -44.07393947, -14.51652494, -46.30693028, -34.21555095,
         1.72780487,   7.91575576, -22.73122714, -12.43339386,
       -54.03096819, -40.39048208, -44.73721656,  -4.0083105 ,
       -50.15781181, -24.46732293])

In [128]:
x

intercept  x1  x2
0           1   2  10
1           1   1   8
2           1  15   8
3           1  16  15
4           1  16  17
5           1  19  10
6           1  10  16
7           1  17  19
8           1   4  18
9           1   5  12
10          1   2  19
11          1  19  10
12          1  16  10
13          1   8  19
14          1   5   3
15          1  13   3
16          1   1   4
17          1  14  11
18          1   4  18
19          1   4   9
20          1   8  11
21          1   7   3
22          1  18  15
23          1   9   7
24          1  10  16
25          1   1   9
26          1  16   4
27          1   1   9
28          1   5   1
29          1  14   8
30          1   9  16
31          1   5  19
32          1   1   2
33          1  10  17
34          1   8   8
35          1  12  18
36          1  14  19
37          1  19  14
38          1  13  19
39          1   1  10
40          1   3   2
41          1   4   1
42          1   5   9
43          1  14  11
44          1   9  19
45          1   2  12
46          1   2  13
47          1  10   7
48          1   5  16
49          1   8  11

In [129]:
w

array([0., 0., 0.])

In [149]:
temp=mycost(y,x,w)


In [131]:
temp

54959.597427040644

In [132]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([ 1213.80045745,  8742.25244289, 19185.23344256])

In [133]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)



In [134]:
my_lr(y,x,0.00001)

46326.90131111341 [-0.11882357 -0.08742252 -0.19185233]
1757.1009734741638 [-0.78383761  1.24674345 -3.07900177]
268.7499739058205 [-0.48494902  1.87251915 -3.5944367 ]
128.54761780124184 [-0.16878712  2.04395214 -3.75333337]
101.02802045747185 [ 0.13354764  2.08635448 -3.80956144]
85.1899711563367 [ 0.41470721  2.09247776 -3.83561704]
72.42216619533431 [ 0.67399501  2.08873724 -3.85225218]
61.69325515864787 [ 0.91249818  2.08262866 -3.86545261]
52.64042216021629 [ 1.13170827  2.07625406 -3.87698653]
44.99877079410484 [ 1.33313618  2.0701798  -3.8874141 ]
38.54806899286538 [ 1.5182102   2.06453688 -3.89694636]
33.10268589751574 [ 1.68825407  2.05933459 -3.9056906 ]
28.505944159047473 [ 1.84448725  2.0545498  -3.91372069]
24.62558614922558 [ 1.9880311   2.05015219 -3.92109744]
21.34996630409426 [ 2.11991615  2.04611135 -3.92787472]
18.584838608598318 [ 2.24108931  2.0423986  -3.93410145]
16.250644916913707 [ 2.35242062  2.03898737 -3.9398224 ]
14.28022590133985 [ 2.45470944  2.0358532  

3.6072699380176663 [ 3.61178501  2.00039985 -4.00453695]
3.6072699376355173 [ 3.61178643  2.00039981 -4.00453702]
3.607269937312938 [ 3.61178774  2.00039977 -4.00453709]
3.6072699370406225 [ 3.61178895  2.00039973 -4.00453715]
3.6072699368107433 [ 3.61179005  2.00039969 -4.00453721]
3.6072699366166923 [ 3.61179107  2.00039966 -4.00453726]
3.6072699364528944 [ 3.611792    2.00039963 -4.00453731]
3.607269936314623 [ 3.61179285  2.00039961 -4.00453735]
3.6072699361978815 [ 3.61179364  2.00039958 -4.00453739]
3.6072699360993434 [ 3.61179437  2.00039956 -4.00453743]
3.607269936016177 [ 3.61179503  2.00039954 -4.00453747]
3.607269935945954 [ 3.61179564  2.00039952 -4.0045375 ]
3.607269935886687 [ 3.6117962   2.00039951 -4.00453753]
3.607269935836639 [ 3.61179672  2.00039949 -4.00453755]
3.607269935794416 [ 3.61179719  2.00039948 -4.00453758]
3.60726993575876 [ 3.61179763  2.00039946 -4.0045376 ]
3.6072699357286644 [ 3.61179803  2.00039945 -4.00453762]
3.6072699357032434 [ 3.61179839  2.00039

3.607269935565614 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656175 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656153 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656264 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656215 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656264 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565624 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656224 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565623 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565625 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656175 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565622 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656175 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656157 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565621 [ 3.61180255  2.00039931 -4.00453785]
3.607269935565614 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656175 [ 3.61180255  2.000

3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255

3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255

3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255

3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255  2.00039931 -4.00453785]
3.6072699355656193 [ 3.61180255

array([ 3.61180255,  2.00039931, -4.00453785])

In [150]:
from sklearn.linear_model import LinearRegression

In [151]:
lr=LinearRegression()

In [152]:
x.shape

(50, 3)

In [153]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [154]:
lr.coef_

array([ 1.99652014, -3.99237991])

In [32]:
lr.intercept_

3.530674802067832